linters:
  package.json:
    - "npmPkgJsonLint"
  "src/**/*.ts":
    - "tslint --fix"
    - "prettier --write"
    - "git add"
    - "jest --bail --findRelatedTests"
ignore:
  - "**/__fixtures__/error.ts"
