language: node_js

node_js:
  - v10
  - v9
  - v8
  - v7
  - v6

before_install:
  npm i -g yarn

matrix:
  allow_failures:
    - node_js: v9
    - node_js: v10

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/adea2c63a919e9b1c7a1
    on_success: change
    on_failure: always
    on_start: never
